name: alefba_app
description: آموزش الفبای فارسی کودکان
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
